Algoritmo "AULA3-EX2"
// Disciplina  : Curso de Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 3  - Ex2
// Autor(a)    : Eduardo Rodrigues
// Data atual  : 1/20/2022

Var
// Seção de Declarações das variáveis
   nome : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Digite o seu nome: ")
   Leia (nome)
   EscrevaL ("Muito prazer, ", nome)


Fimalgoritmo