Algoritmo "AULA3-EX1"
// Disciplina  : Curso de Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 3  - Exemplos
// Autor(a)    : Eduardo Rodrigues
// Data atual  : 1/20/2022

Var
// Seção de Declarações das variáveis 
   nome: caractere
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   nome <- "Eduardo"
   Escreva("Muito prazer, ", nome, ".")
   
Fimalgoritmo

