Algoritmo "AULA9-EX2"
// Disciplina  : [Algoritmo] 
// Professor   : [Gustavo Guanabara] 
// Descricao   : Estruturas de Repetição 1 - AULA 9 - Contar de 0 a 5
// Autor(a)    : Eduardo
// Data atual  : 2/12/2022

Var
   contador : Inteiro

Inicio

   contador <- 0

   Enquanto (contador <= 5) faca
      EscrevaL(contador)
      contador <- contador + 1
   FimEnquanto

   EscrevaL("Terminei de contar !")

Fimalgoritmo

