Algoritmo "AULA9-EX1"
// Disciplina  : [Algoritmo] 
// Professor   : [Gustavo Guanabara] 
// Descricao   : Estruturas de Repetição 1 - Contar de 0 a 10
// Aula        : Curso de Algoritmos #09 - Gustavo Guanabara
// Autor(a)    : Eduardo
// Data atual  : 2/12/2022

Var
   contador : Inteiro

Inicio
   contador <- 0
   Enquanto (contador <= 10) faca
      EscrevaL(contador)
      contador <- contador + 1
   FimEnquanto

Fimalgoritmo

