Algoritmo "conteAte10"
// Disciplina  : [Algoritmo] 
// Professor   : [Gustavo Guanabara] 
// Aula        : [aula09/aula-pratica/conte10Ate00.alg]
// Autor       : Eduardo

Var

   contador : Inteiro

Inicio

   contador <- 0
   
   Enquanto (contador <= 10) faca

      EscrevaL (contador)
      contador <- contador + 1
      
   FimEnquanto
   
   EscrevaL (">>> Terminei de contar !")
   
Fimalgoritmo

