Algoritmo "AULA2-OLAMUNDO"
// Disciplina: [Linguagem e Lógica de programaçao] 
// Professor : [Gustavo Guanabara] 
// Autor(a)    : Eduardo  Rodrigues
// Data atual  : 2/8/2022

Var
// Seção de Declarações das variáveis 

   msg : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   msg <- "Olá, Mundo!
   
   EscrevaL (msg)
   
   EscrevaL ("") // PULA LINHA
   
   EscrevaL ("Mensagem: ", msg)

Fimalgoritmo