Algoritmo "mensagem"
// Disciplina  : [Algoritmo] 
// Professor   : [Gustavo Guanabara] 
// Curso       : Curso de Algoritmos
// Descricao   : EXIBE MENSAGEM NA TELA
// Autor       : Eduardo
// Data atual  : 2/12/2022
Var
// Secao de Declaracoes das variaveis
   mensagem: caractere

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...
   EscrevaL("Digite uma mensagem: ")
   Leia(mensagem)
   EscrevaL("Mensagem >>> ", mensagem)

Fimalgoritmo