Algoritmo "AULA6-EX3"
// Descrição   : Exercícios de Algoritmo Resolvidos - Curso de Algoritmos #06 - Gustavo Guanabara
// Autor(a)    : Eduardo
// Data atual  : 2/8/2022
Var
// Seção de Declarações das variáveis 
   F, C: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Temperatura Fº ? ")
   Leia(F)
   C <- (F - 32) / 1.8
   Escreva("Temperatura Cº ? ", C:4:2) // formatando 4 casas, sendo 2 apos virgula
   
Fimalgoritmo