Algoritmo "AULA3-EX7"
// Disciplina  : Curso de Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Aula 3 - Conversor
// Autor(a)    : Eduardo Rodrigues
// Data atual  : 1/20/2022

Var
// Seção de Declarações das variáveis
   angulo, seno : Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Informe o angulo: ")
   leia(angulo)

   seno <-  Sen(GraupRad(angulo))
   escreva("O seno do angulo ", angulo, " é igual a ",  seno)


Fimalgoritmo