Algoritmo "AULA4-EX2"
// Descrição   : Operadores Lógicos e Relacionais - Curso de Algoritmos #04 - Gustavo Guanabara
// Autor(a)    : Eduardo
// Data atual  : 2/8/2022
Var
// Seção de Declarações das variáveis 
   A, B, C : Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   A <- 2
   B <- 3
   C <- 5

   Escreval((A = B)OU(C > A))        // FALSO OU VERDADEIRO = VERDADEIRO
   Escreval(NAO((A = B)OU(C > A)))     // NAO (VERDADEIRO) = FALSO

Fimalgoritmo