Algoritmo "Combinacoes"
// Disciplina  : [Algoritmo - Estruturas de Repetição 3 - Aula 11]
// Professor   : [Gustavo Guanabara]
// Descrição   : Combinações
// Autor(a)    : EDUARDO RODRIGUES
// Data atual  : 2/20/2022
Var
   // Seção de Declarações das variáveis
   C1 , C2 : Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para C1 <-1 ate 3 Faca
      Para C2 <-1 ate 3 Faca
         EscrevaL (C1, C2)
      FimPara
   FimPara

Fimalgoritmo