Algoritmo "Contar1_Ate10"
// Disciplina  : [Algoritmo - Estruturas de Repetição 3 - Aula 11]
// Professor   : [Gustavo Guanabara]
// Descrição   : Contador 1 ate 10 com Para, omitindo (passo 1)
// Autor(a)    : Eduardo
// Data atual  : 2/20/2022
Var
   // Seção de Declarações das variáveis
   C : Inteiro

Inicio

   EscrevaL ("Teste do Para")
   // --------------------- Para     ---------------------
   Para C <- 1 ate 10 faca
      EscrevaL (C)
   FimPara

Fimalgoritmo