Algoritmo "Contar1Ate10_Para_Passo1"
// Disciplina  : [Algoritmo - Estruturas de Repetição 3 - Aula 11]
// Professor   : [Gustavo Guanabara]
// Descrição   : Contador 1 ate 10 com Para
// Autor(a)    : Eduardo
// Data atual  : 2/20/2022
Var
   // Seção de Declarações das variáveis
   P : Inteiro

Inicio

   EscrevaL ("Teste do Para")
   // --------------------- Para     ---------------------
   Para P <- 1 ate 10 passo 1 faca
      EscrevaL (P)
   FimPara

Fimalgoritmo