Algoritmo "AULA1-EX1"
// Disciplina  : [Linguagem e Lógica de programaçao]
// Professor   : [Gustavo Guanabara]
// Autor(a)    : Eduardo Rodrigues
// Data atual  : 2/8/2022

Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Olá, Mundo !")
   escreval("")
   escreva("Me livrei da maldição !")

Fimalgoritmo