Algoritmo "primeiro"
// Disciplina  : Curso de Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : Exibe mensagem "Ola, Mundo!"
// Data atual  : 1/20/2022
Var
// Seção de Declarações das variáveis
   MSG: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   MSG <- "Ola, Mundo!"
   escreva(MSG)
   escreval("")  // pula linha
   escreva("Fim")

Fimalgoritmo